import { language, ln, dir } from './language'

export const getProvinceName = (provinceId) => {
  if (!provinceId || isNaN(Number(provinceId))) {
    return "222"
  }
  let province = cities.filter(item => item['id'] == Number(provinceId))
  console.log('province:', JSON.stringify(province[0].name), language.key)
  return province[0].name[language.key]
}

export const provinces = [
  { id: 0, name: {fa: '---', en: '---'}, citiesNames: [] },
  { id: 1, name: {fa: "آذربایجان شرقی", en: "Azerbaijan, East"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبش احمد' , en: ''}},
      {id: 2, name: {fa: 'آچاچی', en: ''}},
      {id: 3, name: {fa: 'آذرشهر', en: ''}},
      {id: 4, name: {fa: 'آفکند', en: ''}},
      {id: 5, name: {fa: 'اسکو', en: ''}},
      {id: 6, name: {fa: 'اهر', en: ''}},
      {id: 7, name: {fa: 'ایلخچی', en: ''}},
      {id: 8, name: {fa: 'باسمنج', en: ''}},
      {id: 9, name: {fa: 'بخشایش', en: ''}},
      {id: 10, name: {fa: 'بستان آباد', en: ''}},
      {id: 11, name: {fa: 'بناب', en: ''}},
      {id: 12, name: {fa: 'بناب مرند', en: ''}},
      {id: 13, name: {fa: 'تبریز', en: ''}},
      {id: 14, name: {fa: 'ترک', en: ''}},
      {id: 15, name: {fa: 'تیمورلو', en: ''}},
      {id: 16, name: {fa: 'ترکمانچای', en: ''}},
      {id: 17, name: {fa: 'تسوج', en: ''}},
      {id: 18, name: {fa: 'تیکمه داش', en: ''}},
      {id: 19, name: {fa: 'جلفا', en: ''}},
      {id: 20, name: {fa: 'جوان قلعه', en: ''}},
      {id: 21, name: {fa: 'خاروانا', en: ''}},
      {id: 22, name: {fa: 'خامنه', en: ''}},
      {id: 23, name: {fa: 'خداجو', en: ''}},
      {id: 24, name: {fa: 'خسروشاه', en: ''}},
      {id: 25, name: {fa: 'خمارلو', en: ''}},
      {id: 26, name: {fa: 'خواجه', en: ''}},
      {id: 27, name: {fa: 'دوزدوزان', en: ''}},
      {id: 28, name: {fa: 'زرنق', en: ''}},
      {id: 29, name: {fa: 'زنوز', en: ''}},
      {id: 30, name: {fa: 'سراب', en: ''}},
      {id: 31, name: {fa: 'سردرود', en: ''}},
      {id: 32, name: {fa: 'سهند', en: ''}},
      {id: 33, name: {fa: 'سیس', en: ''}},
      {id: 34, name: {fa: 'سیه رود', en: ''}},
      {id: 35, name: {fa: 'شبستر', en: ''}},
      {id: 36, name: {fa: 'شربیان', en: ''}},
      {id: 37, name: {fa: 'شرفخانه', en: ''}},
      {id: 38, name: {fa: 'شند آباد', en: ''}},
      {id: 39, name: {fa: 'صوفیان', en: ''}},
      {id: 40, name: {fa: 'عجب شیر', en: ''}},
      {id: 41, name: {fa: 'قره آغاج', en: ''}},
      {id: 42, name: {fa: 'کشکسرای', en: ''}},
      {id: 43, name: {fa: 'کلوانق', en: ''}},
      {id: 44, name: {fa: 'کلیبر', en: ''}},
      {id: 45, name: {fa: 'کوزه کنان', en: ''}},
      {id: 46, name: {fa: 'گوگان', en: ''}},
      {id: 47, name: {fa: 'لیلان', en: ''}},
      {id: 48, name: {fa: 'مبارک شهر', en: ''}},
      {id: 49, name: {fa: 'مراغه', en: ''}},
      {id: 50, name: {fa: 'مرند', en: ''}},
      {id: 51, name: {fa: 'ملکان', en: ''}},
      {id: 52, name: {fa: 'ممقان', en: ''}},
      {id: 53, name: {fa: 'مهربان', en: ''}},
      {id: 54, name: {fa: 'میانه', en: ''}},
      {id: 55, name: {fa: 'نظرکهریزی', en: ''}},
      {id: 56, name: {fa: 'وایقان', en: ''}},
      {id: 57, name: {fa: 'ورزقان', en: ''}},
      {id: 58, name: {fa: 'هادیشهر', en: ''}},
      {id: 59, name: {fa: 'هریس', en: ''}},
      {id: 60, name: {fa: 'هشترود', en: ''}},
      {id: 61, name: {fa: 'هوراند', en: ''}},
      {id: 62, name: {fa: 'یامچی', en: ''}},
  ]},

  { id: 2, name: {fa: "آذربایجان غربی", en: "Azerbaijan, West"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آواجیق', en: ''}},
      {id: 2, name: {fa: 'ارومیه', en: ''}},
      {id: 3, name: {fa: 'اشنویه', en: ''}},
      {id: 4, name: {fa: 'ایواوغلی', en: ''}},
      {id: 5, name: {fa: 'باروق', en: ''}},
      {id: 6, name: {fa: 'بازرگان', en: ''}},
      {id: 7, name: {fa: 'بوکان', en: ''}},
      {id: 8, name: {fa: 'پلدشت', en: ''}},
      {id: 9, name: {fa: 'پیرانشهر', en: ''}},
      {id: 10, name: {fa: 'تازه شهر', en: ''}},
      {id: 11, name: {fa: 'تکاب', en: ''}},
      {id: 12, name: {fa: 'چهاربرج', en: ''}},
      {id: 13, name: {fa: 'خلیفان', en: ''}},
      {id: 14, name: {fa: 'خوی', en: ''}},
      {id: 15, name: {fa: 'دیزج دیز', en: ''}},
      {id: 16, name: {fa: 'ربط', en: ''}},
      {id: 17, name: {fa: 'زرآباد', en: ''}},
      {id: 18, name: {fa: 'سردشت', en: ''}},
      {id: 19, name: {fa: 'سرو', en: ''}},
      {id: 20, name: {fa: 'سلماس', en: ''}},
      {id: 21, name: {fa: 'سیلوانه', en: ''}},
      {id: 22, name: {fa: 'سیمیته', en: ''}},
      {id: 23, name: {fa: 'سیه چشمه', en: ''}},
      {id: 24, name: {fa: 'شاهین دژ', en: ''}},
      {id: 25, name: {fa: 'شوط', en: ''}},
      {id: 26, name: {fa: 'فیرورق', en: ''}},
      {id: 27, name: {fa: 'قره ضیاءالدین', en: ''}},
      {id: 28, name: {fa: 'قطور', en: ''}},
      {id: 29, name: {fa: 'قوشچی', en: ''}},
      {id: 30, name: {fa: 'کشاورز', en: ''}},
      {id: 31, name: {fa: 'گردکشانه', en: ''}},
      {id: 32, name: {fa: 'ماکو', en: ''}},
      {id: 33, name: {fa: 'محمدیار', en: ''}},
      {id: 34, name: {fa: 'محمودآباد', en: ''}},
      {id: 35, name: {fa: 'مرگنلر', en: ''}},
      {id: 36, name: {fa: 'مهاباد', en: ''}},
      {id: 37, name: {fa: 'میاندوآب', en: ''}},
      {id: 38, name: {fa: 'میرآباد', en: ''}},
      {id: 39, name: {fa: 'نازک علیا', en: ''}},
      {id: 40, name: {fa: 'نالوس', en: ''}},
      {id: 41, name: {fa: 'نقده', en: ''}},
      {id: 42, name: {fa: 'نوشین شهر', en: ''}},
  ]},
  { id: 3, name: {fa: "اردبیل", en: "Ardabil"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبی بیگلو', en: ''}},
      {id: 2, name: {fa: 'اردبیل', en: ''}},
      {id: 3, name: {fa: 'اسلام آباد', en: ''}},
      {id: 4, name: {fa: 'اصلاندوز', en: ''}},
      {id: 5, name: {fa: 'بیله سوار', en: ''}},
      {id: 6, name: {fa: 'پارس آباد', en: ''}},
      {id: 7, name: {fa: 'تازه کند', en: ''}},
      {id: 8, name: {fa: 'تازه کند انگوت",', en: ''}},
      {id: 9, name: {fa: 'جعفر آباد', en: ''}},
      {id: 10, name: {fa: 'خلخال', en: ''}},
      {id: 11, name: {fa: 'رضی', en: ''}},
      {id: 12, name: {fa: 'سرعین', en: ''}},
      {id: 13, name: {fa: 'عنبران', en: ''}},
      {id: 14, name: {fa: 'فخر آباد', en: ''}},
      {id: 15, name: {fa: 'قصابه', en: ''}},
      {id: 16, name: {fa: 'کلور', en: ''}},
      {id: 17, name: {fa: 'کوراییم', en: ''}},
      {id: 18, name: {fa: 'گرمی', en: ''}},
      {id: 19, name: {fa: 'گیوی', en: ''}},
      {id: 20, name: {fa: 'لاهرود', en: ''}},
      {id: 21, name: {fa: 'مرادلو', en: ''}},
      {id: 22, name: {fa: 'مشگین شهر', en: ''}},
      {id: 23, name: {fa: 'نمین', en: ''}},
      {id: 24, name: {fa: 'نیر', en: ''}},
      {id: 25, name: {fa: 'هشجین', en: ''}},
      {id: 26, name: {fa: 'هیر', en: ''}},
  ]},
  { id: 4, name: {fa: "اصفهان", en: "Isfahan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ابریشم', en: ''}},
      {id: 2, name: {fa: 'ابوزید آباد', en: ''}},
      {id: 3, name: {fa: 'اردستان', en: ''}},
      {id: 4, name: {fa: 'اژیه', en: ''}},
      {id: 5, name: {fa: 'اصفهان', en: ''}},
      {id: 6, name: {fa: 'افوس', en: ''}},
      {id: 7, name: {fa: 'انارک', en: ''}},
      {id: 8, name: {fa: 'آران و بیدگل', en: ''}},
      {id: 9, name: {fa: 'ایمان شهر', en: ''}},
      {id: 10, name: {fa: 'بادرود', en: ''}},
      {id: 11, name: {fa: 'باغ بهادران', en: ''}},
      {id: 12, name: {fa: 'بافران', en: ''}},
      {id: 13, name: {fa: 'برزک', en: ''}},
      {id: 14, name: {fa: 'برف انبار', en: ''}},
      {id: 15, name: {fa: 'بهاران شهر', en: ''}},
      {id: 16, name: {fa: 'بهارستان', en: ''}},
      {id: 17, name: {fa: 'بوئین و میاندشت', en: ''}},
      {id: 18, name: {fa: 'پیربکران', en: ''}},
      {id: 19, name: {fa: 'تودشک', en: ''}},
      {id: 20, name: {fa: 'تیران', en: ''}},
      {id: 21, name: {fa: 'جندق', en: ''}},
      {id: 22, name: {fa: 'جوزدان', en: ''}},
      {id: 23, name: {fa: 'جوشقان قالی', en: ''}},
      {id: 24, name: {fa: 'چادگان', en: ''}},
      {id: 25, name: {fa: 'چرمهین', en: ''}},
      {id: 26, name: {fa: 'چم گردان', en: ''}},
      {id: 27, name: {fa: 'حبیب آباد', en: ''}},
      {id: 28, name: {fa: 'حسن آباد', en: ''}},
      {id: 29, name: {fa: 'حنا', en: ''}},
      {id: 30, name: {fa: 'خالد آباد', en: ''}},
      {id: 31, name: {fa: 'خمینی شهر', en: ''}},
      {id: 32, name: {fa: 'خوانسار', en: ''}},
      {id: 33, name: {fa: 'خور', en: ''}},
      {id: 34, name: {fa: 'خوراسگان', en: ''}},
      {id: 35, name: {fa: 'خورزوق', en: ''}},
      {id: 36, name: {fa: 'داران', en: ''}},
      {id: 37, name: {fa: 'دامنه', en: ''}},
      {id: 38, name: {fa: 'درچه پیاز', en: ''}},
      {id: 39, name: {fa: 'دستگرد', en: ''}},
      {id: 40, name: {fa: 'دهاقان', en: ''}},
      {id: 41, name: {fa: 'دهق', en: ''}},
      {id: 42, name: {fa: 'دولت آباد', en: ''}},
      {id: 43, name: {fa: 'دیزیچه', en: ''}},
      {id: 44, name: {fa: 'راوند', en: ''}},
      {id: 45, name: {fa: 'رزوه', en: ''}},
      {id: 46, name: {fa: 'رضوان شهر', en: ''}},
      {id: 47, name: {fa: 'زاینده رود', en: ''}},
      {id: 48, name: {fa: 'زرین شهر', en: ''}},
      {id: 49, name: {fa: 'زواره', en: ''}},
      {id: 50, name: {fa: 'زیار', en: ''}},
      {id: 51, name: {fa: 'زیبا شهر', en: ''}},
      {id: 52, name: {fa: 'سده لنجان', en: ''}},
      {id: 53, name: {fa: 'سفید شهر', en: ''}},
      {id: 54, name: {fa: 'سگزی', en: ''}},
      {id: 55, name: {fa: 'سمیرم', en: ''}},
      {id: 56, name: {fa: 'سین', en: ''}},
      {id: 57, name: {fa: 'شاپورآباد', en: ''}},
      {id: 58, name: {fa: 'شاهین شهر', en: ''}},
      {id: 59, name: {fa: 'شهرضا', en: ''}},
      {id: 60, name: {fa: 'طالخونچه', en: ''}},
      {id: 61, name: {fa: 'عسگران', en: ''}},
      {id: 62, name: {fa: 'علویجه', en: ''}},
      {id: 63, name: {fa: 'فرخی', en: ''}},
      {id: 64, name: {fa: 'فریدون شهر', en: ''}},
      {id: 65, name: {fa: 'فلاورجان', en: ''}},
      {id: 66, name: {fa: 'فولادشهر', en: ''}},
      {id: 67, name: {fa: 'قهدریجان', en: ''}},
      {id: 68, name: {fa: 'قمصر', en: ''}},
      {id: 69, name: {fa: 'کاشان', en: ''}},
      {id: 70, name: {fa: 'کرکوند', en: ''}},
      {id: 71, name: {fa: 'کلیشاد و سودرجان",', en: ''}},
      {id: 72, name: {fa: 'کمشجه', en: ''}},
      {id: 73, name: {fa: 'کمه', en: ''}},
      {id: 74, name: {fa: 'کهریزسنگ', en: ''}},
      {id: 75, name: {fa: 'کوشک', en: ''}},
      {id: 76, name: {fa: 'کوهپایه', en: ''}},
      {id: 77, name: {fa: 'گز', en: ''}},
      {id: 78, name: {fa: 'گلپایگان', en: ''}},
      {id: 79, name: {fa: 'گل دشت', en: ''}},
      {id: 80, name: {fa: 'گل شهر', en: ''}},
      {id: 81, name: {fa: 'گلشن', en: ''}},
      {id: 82, name: {fa: 'گوگد', en: ''}},
      {id: 83, name: {fa: 'مبارکه', en: ''}},
      {id: 84, name: {fa: 'محمد آباد', en: ''}},
      {id: 85, name: {fa: 'محسن آباد', en: ''}},
      {id: 86, name: {fa: 'مشکات', en: ''}},
      {id: 87, name: {fa: 'منظریه', en: ''}},
      {id: 88, name: {fa: 'مهاباد', en: ''}},
      {id: 89, name: {fa: 'میمه', en: ''}},
      {id: 90, name: {fa: 'نایین', en: ''}},
      {id: 91, name: {fa: 'نوش آباد', en: ''}},
      {id: 92, name: {fa: 'نجف آباد', en: ''}},
      {id: 93, name: {fa: 'نصر آباد', en: ''}},
      {id: 94, name: {fa: 'نطنز', en: ''}},
      {id: 95, name: {fa: 'نیاسر', en: ''}},
      {id: 96, name: {fa: 'نیک آباد', en: ''}},
      {id: 97, name: {fa: 'ورزنه', en: ''}},
      {id: 98, name: {fa: 'ورنامخواست', en: ''}},
      {id: 99, name: {fa: 'ونک', en: ''}},
      {id: 100, name: {fa: 'هرند', en: ''}},
  ]},
  { id: 5, name: {fa: "البرز", en: "Alborz"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آسارا', en: ''}},
      {id: 2, name: {fa: 'اشتهارد', en: ''}},
      {id: 3, name: {fa: 'تنکمان', en: ''}},
      {id: 4, name: {fa: 'چهار باغ', en: ''}},
      {id: 5, name: {fa: 'شهر جدید هشتگرد', en: ''}},
      {id: 6, name: {fa: 'طالقان', en: ''}},
      {id: 7, name: {fa: 'فردیس', en: ''}},
      {id: 8, name: {fa: 'کرج', en: ''}},
      {id: 9, name: {fa: 'کمال شهر', en: ''}},
      {id: 10, name: {fa: 'کوهسار', en: ''}},
      {id: 11, name: {fa: 'گرمدره', en: ''}},
      {id: 12, name: {fa: 'گلسار', en: ''}},
      {id: 13, name: {fa: 'ماهدشت', en: ''}},
      {id: 14, name: {fa: 'محمد شهر', en: ''}},
      {id: 15, name: {fa: 'مشکین دشت', en: ''}},
      {id: 16, name: {fa: 'نظر آباد', en: ''}},
      {id: 17, name: {fa: 'هشتگرد', en: ''}},
  ]},
  { id: 6, name: {fa: "ایلام", en: "Ilam"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبدانان', en: ''}},
      {id: 2, name: {fa: 'آسمان آباد', en: ''}},
      {id: 3, name: {fa: 'ارکواز', en: ''}},
      {id: 4, name: {fa: 'ایلام', en: ''}},
      {id: 5, name: {fa: 'ایوان', en: ''}},
      {id: 6, name: {fa: 'بدره', en: ''}},
      {id: 7, name: {fa: 'بلاوه', en: ''}},
      {id: 8, name: {fa: 'پهله', en: ''}},
      {id: 9, name: {fa: 'توحید', en: ''}},
      {id: 10, name: {fa: 'چوار', en: ''}},
      {id: 11, name: {fa: 'دره شهر', en: ''}},
      {id: 12, name: {fa: 'دلگشا', en: ''}},
      {id: 13, name: {fa: 'دهلران', en: ''}},
      {id: 14, name: {fa: 'زرنه', en: ''}},
      {id: 15, name: {fa: 'سرابله', en: ''}},
      {id: 16, name: {fa: 'سراب باغ', en: ''}},
      {id: 17, name: {fa: 'صالح آباد', en: ''}},
      {id: 18, name: {fa: 'لومار', en: ''}},
      {id: 19, name: {fa: 'ماژین', en: ''}},
      {id: 20, name: {fa: 'مورموری', en: ''}},
      {id: 21, name: {fa: 'موسیان', en: ''}},
      {id: 22, name: {fa: 'مهر', en: ''}},
      {id: 23, name: {fa: 'مهران', en: ''}},
      {id: 24, name: {fa: 'میمه', en: ''}},
  ]},
  { id: 7, name: {fa: "بوشهر", en: "Bushehr"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آباد', en: ''}},
      {id: 2, name: {fa: 'آب پخش', en: ''}},
      {id: 3, name: {fa: 'آبدان', en: ''}},
      {id: 4, name: {fa: 'امام حسن', en: ''}},
      {id: 5, name: {fa: 'انارستان', en: ''}},
      {id: 6, name: {fa: 'اهرم', en: ''}},
      {id: 7, name: {fa: 'بادوله', en: ''}},
      {id: 8, name: {fa: 'برازجان', en: ''}},
      {id: 9, name: {fa: 'بردخون', en: ''}},
      {id: 10, name: {fa: 'بردستان', en: ''}},
      {id: 11, name: {fa: 'بوشهر', en: ''}},
      {id: 12, name: {fa: 'بندر دیّر', en: ''}},
      {id: 13, name: {fa: 'بندر دیلم', en: ''}},
      {id: 14, name: {fa: 'بندر ریگ', en: ''}},
      {id: 15, name: {fa: 'بندر سیراف', en: ''}},
      {id: 16, name: {fa: 'بندر کنگان', en: ''}},
      {id: 17, name: {fa: 'بندر گناوه', en: ''}},
      {id: 18, name: {fa: 'بنک', en: ''}},
      {id: 19, name: {fa: 'بوشکان', en: ''}},
      {id: 20, name: {fa: 'تنگ ارم', en: ''}},
      {id: 21, name: {fa: 'جم', en: ''}},
      {id: 22, name: {fa: 'چغادک', en: ''}},
      {id: 23, name: {fa: 'خارگ', en: ''}},
      {id: 24, name: {fa: 'خورموج', en: ''}},
      {id: 25, name: {fa: 'دالکی', en: ''}},
      {id: 26, name: {fa: 'دلوار', en: ''}},
      {id: 27, name: {fa: 'دوراهک', en: ''}},
      {id: 28, name: {fa: 'ریز', en: ''}},
      {id: 29, name: {fa: 'سعدآباد', en: ''}},
      {id: 30, name: {fa: 'شبانکاره', en: ''}},
      {id: 31, name: {fa: 'شنبه', en: ''}},
      {id: 32, name: {fa: 'عالی شهر', en: ''}},
      {id: 33, name: {fa: 'بندر عسلویه', en: ''}},
      {id: 34, name: {fa: 'کاکی', en: ''}},
      {id: 35, name: {fa: 'کلمه', en: ''}},
      {id: 36, name: {fa: 'نخل تقی', en: ''}},
      {id: 37, name: {fa: 'وحدتیه', en: ''}},
  ]},
  { id: 8, name: {fa: "تهران", en: "Tehran"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبسرد', en: ''}},
      {id: 2, name: {fa: 'آبعلی', en: ''}},
      {id: 3, name: {fa: 'ارجمند', en: ''}},
      {id: 4, name: {fa: 'اسلام شهر', en: ''}},
      {id: 5, name: {fa: 'اندیشه', en: ''}},
      {id: 6, name: {fa: 'باغستان', en: ''}},
      {id: 7, name: {fa: 'باقر شهر', en: ''}},
      {id: 8, name: {fa: 'بومهن', en: ''}},
      {id: 9, name: {fa: 'پاکدشت', en: ''}},
      {id: 10, name: {fa: 'پردیس', en: ''}},
      {id: 11, name: {fa: 'پرند', en: ''}},
      {id: 12, name: {fa: 'پیشوا', en: ''}},
      {id: 13, name: {fa: 'تهران', en: ''}},
      {id: 14, name: {fa: 'جوادآباد', en: ''}},
      {id: 15, name: {fa: 'چهاردانگه', en: ''}},
      {id: 16, name: {fa: 'حسن آباد', en: ''}},
      {id: 17, name: {fa: 'دماوند', en: ''}},
      {id: 18, name: {fa: 'رباط کریم', en: ''}},
      {id: 19, name: {fa: 'رودهن', en: ''}},
      {id: 20, name: {fa: 'شاهد شهر', en: ''}},
      {id: 21, name: {fa: 'شریف آباد', en: ''}},
      {id: 22, name: {fa: 'شمشک', en: ''}},
      {id: 23, name: {fa: 'شهرری', en: ''}},
      {id: 24, name: {fa: 'شهریار', en: ''}},
      {id: 25, name: {fa: 'صالحیه', en: ''}},
      {id: 26, name: {fa: 'صبا شهر', en: ''}},
      {id: 27, name: {fa: 'صفا دشت', en: ''}},
      {id: 28, name: {fa: 'فردوسیه', en: ''}},
      {id: 29, name: {fa: 'فشم', en: ''}},
      {id: 30, name: {fa: 'فیروزکوه', en: ''}},
      {id: 31, name: {fa: 'قدس', en: ''}},
      {id: 32, name: {fa: 'قرچک', en: ''}},
      {id: 33, name: {fa: 'کهریزک', en: ''}},
      {id: 34, name: {fa: 'کیلان', en: ''}},
      {id: 35, name: {fa: 'گلستان', en: ''}},
      {id: 36, name: {fa: 'لواسان', en: ''}},
      {id: 37, name: {fa: 'ملارد', en: ''}},
      {id: 38, name: {fa: 'نسیم شهر', en: ''}},
      {id: 39, name: {fa: 'نصیر شهر', en: ''}},
      {id: 40, name: {fa: 'وحیدیه', en: ''}},
      {id: 41, name: {fa: 'ورامین', en: ''}},
  ]},
  { id: 9, name: {fa: "چهارمحال و بختیاری", en: "Chahar Mahaal and Bakhtiari"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آلونی', en: ''}},
      {id: 2, name: {fa: 'اردل', en: ''}},
      {id: 3, name: {fa: 'باباحیدر', en: ''}},
      {id: 4, name: {fa: 'بازفت', en: ''}},
      {id: 5, name: {fa: 'بروجن', en: ''}},
      {id: 6, name: {fa: 'بلداجی', en: ''}},
      {id: 7, name: {fa: 'بن', en: ''}},
      {id: 8, name: {fa: 'پردنجان', en: ''}},
      {id: 9, name: {fa: 'جونقان', en: ''}},
      {id: 10, name: {fa: 'چلگرد', en: ''}},
      {id: 11, name: {fa: 'چلیچه', en: ''}},
      {id: 12, name: {fa: 'دستنا', en: ''}},
      {id: 13, name: {fa: 'دشتک', en: ''}},
      {id: 14, name: {fa: 'سامان', en: ''}},
      {id: 15, name: {fa: 'سرخون', en: ''}},
      {id: 16, name: {fa: 'سفید دشت', en: ''}},
      {id: 17, name: {fa: 'سودجان', en: ''}},
      {id: 18, name: {fa: 'سورشجان', en: ''}},
      {id: 19, name: {fa: 'شلمزار', en: ''}},
      {id: 20, name: {fa: 'شهرکرد', en: ''}},
      {id: 21, name: {fa: 'طاقانک', en: ''}},
      {id: 22, name: {fa: 'فارسان', en: ''}},
      {id: 23, name: {fa: 'فرادنبه', en: ''}},
      {id: 24, name: {fa: 'فرخ شهر', en: ''}},
      {id: 25, name: {fa: 'کاج', en: ''}},
      {id: 26, name: {fa: 'کیان', en: ''}},
      {id: 27, name: {fa: 'گندمان', en: ''}},
      {id: 28, name: {fa: 'گهرو', en: ''}},
      {id: 29, name: {fa: 'گوجان', en: ''}},
      {id: 30, name: {fa: 'لردگان', en: ''}},
      {id: 31, name: {fa: 'مال خلیفه', en: ''}},
      {id: 32, name: {fa: 'منج', en: ''}},
      {id: 33, name: {fa: 'ناغان', en: ''}},
      {id: 34, name: {fa: 'نافچ', en: ''}},
      {id: 35, name: {fa: 'نقنه', en: ''}},
      {id: 36, name: {fa: 'هفشجان', en: ''}},
      {id: 37, name: {fa: 'وردنجان', en: ''}},
  ]},
  { id: 10, name: {fa: "خراسان جنوبی", en: "Khorasan, South"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آرین‌شهر', en: ''}},
      {id: 2, name: {fa: 'ارسک', en: ''}},
      {id: 3, name: {fa: 'اسدی', en: ''}},
      {id: 4, name: {fa: 'اسفد', en: ''}},
      {id: 5, name: {fa: 'اسلا', en: ''}},
      {id: 6, name: {fa: 'آیسک', en: ''}},
      {id: 7, name: {fa: 'بشرو', en: ''}},
      {id: 8, name: {fa: 'بیرج', en: ''}},
      {id: 9, name: {fa: 'حاجی‌آباد', en: ''}},
      {id: 10, name: {fa: 'خضری دشت بیاض', en: ''}},
      {id: 11, name: {fa: 'خوسف', en: ''}},
      {id: 12, name: {fa: 'دیهوک', en: ''}},
      {id: 13, name: {fa: 'زهان', en: ''}},
      {id: 14, name: {fa: 'سرایان', en: ''}},
      {id: 15, name: {fa: 'سربیشه', en: ''}},
      {id: 16, name: {fa: 'سه قلعه', en: ''}},
      {id: 17, name: {fa: 'شوسف', en: ''}},
      {id: 18, name: {fa: 'طبس', en: ''}},
      {id: 19, name: {fa: 'طبس مسینا', en: ''}},
      {id: 20, name: {fa: 'عشق آباد', en: ''}},
      {id: 21, name: {fa: 'فردوس', en: ''}},
      {id: 23, name: {fa: 'قائن', en: ''}},
      {id: 24, name: {fa: 'قهستان', en: ''}},
      {id: 25, name: {fa: 'گزیک', en: ''}},
      {id: 26, name: {fa: 'محمد شهر', en: ''}},
      {id: 27, name: {fa: 'مود', en: ''}},
      {id: 28, name: {fa: 'نهبندان', en: ''}},
      {id: 29, name: {fa: 'نیمبلوک', en: ''}},
  ]},
  { id: 11, name: {fa: "خراسان رضوی", en: "Khorasan, Razavi"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'احمد آباد صولت', en: ''}},
      {id: 2, name: {fa: 'انابد', en: ''}},
      {id: 3, name: {fa: 'باجگیران', en: ''}},
      {id: 4, name: {fa: 'باخرز', en: ''}},
      {id: 5, name: {fa: 'بار', en: ''}},
      {id: 6, name: {fa: 'بایگ', en: ''}},
      {id: 7, name: {fa: 'بجستان', en: ''}},
      {id: 8, name: {fa: 'بردسکن', en: ''}},
      {id: 9, name: {fa: 'بیدخت', en: ''}},
      {id: 10, name: {fa: 'تایباد', en: ''}},
      {id: 11, name: {fa: 'تربت جام', en: ''}},
      {id: 12, name: {fa: 'تربت حیدریه', en: ''}},
      {id: 13, name: {fa: 'جغتای', en: ''}},
      {id: 14, name: {fa: 'جنگل', en: ''}},
      {id: 15, name: {fa: 'چاپشلو', en: ''}},
      {id: 16, name: {fa: 'چکنه', en: ''}},
      {id: 17, name: {fa: 'چناران', en: ''}},
      {id: 18, name: {fa: 'خرو', en: ''}},
      {id: 19, name: {fa: 'خلیل آباد', en: ''}},
      {id: 20, name: {fa: 'خواف', en: ''}},
      {id: 21, name: {fa: 'داورزن', en: ''}},
      {id: 23, name: {fa: 'درود', en: ''}},
      {id: 24, name: {fa: 'درگز', en: ''}},
      {id: 25, name: {fa: 'دولت آباد', en: ''}},
      {id: 26, name: {fa: 'رباط سنگ', en: ''}},
      {id: 27, name: {fa: 'رشتخوار', en: ''}},
      {id: 28, name: {fa: 'رضویه', en: ''}},
      {id: 29, name: {fa: 'رودآب', en: ''}},
      {id: 30, name: {fa: 'ریوش', en: ''}},
      {id: 31, name: {fa: 'سبزوار', en: ''}},
      {id: 32, name: {fa: 'سرخس', en: ''}},
      {id: 33, name: {fa: 'سفید سنگ', en: ''}},
      {id: 34, name: {fa: 'سلامی', en: ''}},
      {id: 35, name: {fa: 'سلطان آباد', en: ''}},
      {id: 36, name: {fa: 'سنگان', en: ''}},
      {id: 37, name: {fa: 'شادمهر', en: ''}},
      {id: 38, name: {fa: 'شاندیز', en: ''}},
      {id: 39, name: {fa: 'ششتمد', en: ''}},
      {id: 40, name: {fa: 'شهرآباد', en: ''}},
      {id: 41, name: {fa: 'شهرزو', en: ''}},
      {id: 42, name: {fa: 'صالح آباد', en: ''}},
      {id: 43, name: {fa: 'طرقبه', en: ''}},
      {id: 44, name: {fa: 'عشق آباد', en: ''}},
      {id: 45, name: {fa: 'فرهادگرد', en: ''}},
      {id: 46, name: {fa: 'فریمان', en: ''}},
      {id: 47, name: {fa: 'فیروزه', en: ''}},
      {id: 48, name: {fa: 'فیض آباد', en: ''}},
      {id: 49, name: {fa: 'قاسم آباد', en: ''}},
      {id: 50, name: {fa: 'قدمگاه', en: ''}},
      {id: 51, name: {fa: 'قلندرآباد', en: ''}},
      {id: 52, name: {fa: 'قوچان', en: ''}},
      {id: 53, name: {fa: 'کاخک', en: ''}},
      {id: 54, name: {fa: 'کاریز', en: ''}},
      {id: 55, name: {fa: 'کاشمر', en: ''}},
      {id: 56, name: {fa: 'کدکن', en: ''}},
      {id: 57, name: {fa: 'کلات', en: ''}},
      {id: 58, name: {fa: 'کندر', en: ''}},
      {id: 59, name: {fa: 'گلبهار', en: ''}},
      {id: 60, name: {fa: 'گلمکان', en: ''}},
      {id: 61, name: {fa: 'گناباد', en: ''}},
      {id: 62, name: {fa: 'لطف آباد', en: ''}},
      {id: 63, name: {fa: 'مزداوند', en: ''}},
      {id: 64, name: {fa: 'مشهد', en: ''}},
      {id: 65, name: {fa: 'مشهد ریزه', en: ''}},
      {id: 66, name: {fa: 'ملک آباد', en: ''}},
      {id: 67, name: {fa: 'نشتیفان', en: ''}},
      {id: 68, name: {fa: 'نصرآباد', en: ''}},
      {id: 69, name: {fa: 'نقاب', en: ''}},
      {id: 70, name: {fa: 'نوخندان', en: ''}},
      {id: 71, name: {fa: 'نیشابور', en: ''}},
      {id: 72, name: {fa: 'نیل شهر', en: ''}},
      {id: 73, name: {fa: 'همت آباد', en: ''}},
      {id: 74, name: {fa: 'یونسی', en: ''}},
  ]},
  { id: 12, name: {fa: "خراسان شمالی", en: "Khorasan, North"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آشخانه', en: ''}},
      {id: 2, name: {fa: 'آوا', en: ''}},
      {id: 3, name: {fa: 'اسفراین', en: ''}},
      {id: 4, name: {fa: 'ایور', en: ''}},
      {id: 5, name: {fa: 'بجنورد', en: ''}},
      {id: 6, name: {fa: 'پیش قلعه', en: ''}},
      {id: 7, name: {fa: 'تیتکانلو', en: ''}},
      {id: 8, name: {fa: 'جاجرم', en: ''}},
      {id: 9, name: {fa: 'چناران شهر', en: ''}},
      {id: 10, name: {fa: 'حصار گرم خان', en: ''}},
      {id: 11, name: {fa: 'درق', en: ''}},
      {id: 12, name: {fa: 'راز', en: ''}},
      {id: 13, name: {fa: 'زیارت', en: ''}},
      {id: 14, name: {fa: 'سنخواست', en: ''}},
      {id: 15, name: {fa: 'شوقان', en: ''}},
      {id: 16, name: {fa: 'شیروان', en: ''}},
      {id: 17, name: {fa: 'صفی آباد', en: ''}},
      {id: 18, name: {fa: 'فاروج', en: ''}},
      {id: 19, name: {fa: 'قاضی', en: ''}},
      {id: 20, name: {fa: 'قوشخانه', en: ''}},
      {id: 21, name: {fa: 'گرمه', en: ''}},
      {id: 23, name: {fa: 'لوجلی', en: ''}},
  ]},
  { id: 13, name: {fa: "خوزستان", en: "Khuzestan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبادان', en: ''}},
      {id: 2, name: {fa: 'آزادی', en: ''}},
      {id: 3, name: {fa: 'آغاجاری', en: ''}},
      {id: 4, name: {fa: 'ابوحمیظه', en: ''}},
      {id: 5, name: {fa: 'اروندکنار', en: ''}},
      {id: 6, name: {fa: 'الوان', en: ''}},
      {id: 7, name: {fa: 'الهایی', en: ''}},
      {id: 8, name: {fa: 'امیدیه', en: ''}},
      {id: 9, name: {fa: 'اندیمشک', en: ''}},
      {id: 10, name: {fa: 'اهواز', en: ''}},
      {id: 11, name: {fa: 'ایذه', en: ''}},
      {id: 12, name: {fa: 'باغ ملک', en: ''}},
      {id: 13, name: {fa: 'بستان', en: ''}},
      {id: 14, name: {fa: 'بندر امام خمینی', en: ''}},
      {id: 15, name: {fa: 'بندر ماهشهر', en: ''}},
      {id: 16, name: {fa: 'بهبهان', en: ''}},
      {id: 17, name: {fa: 'بیدروبه', en: ''}},
      {id: 18, name: {fa: 'ترکالکی', en: ''}},
      {id: 19, name: {fa: 'تشان', en: ''}},
      {id: 20, name: {fa: 'جایزان', en: ''}},
      {id: 21, name: {fa: 'جنت مکان', en: ''}},
      {id: 23, name: {fa: 'چم گلک', en: ''}},
      {id: 24, name: {fa: 'چمران', en: ''}},
      {id: 25, name: {fa: 'حر ریاحی', en: ''}},
      {id: 26, name: {fa: 'حسینیه', en: ''}},
      {id: 27, name: {fa: 'حمزه', en: ''}},
      {id: 28, name: {fa: 'حمیدیه', en: ''}},
      {id: 29, name: {fa: 'خرمشهر', en: ''}},
      {id: 30, name: {fa: 'خنافره', en: ''}},
      {id: 31, name: {fa: 'دارخوین', en: ''}},
      {id: 32, name: {fa: 'دزآب', en: ''}},
      {id: 33, name: {fa: 'دزفول', en: ''}},
      {id: 34, name: {fa: 'دهدز', en: ''}},
      {id: 35, name: {fa: 'رامشیر', en: ''}},
      {id: 36, name: {fa: 'رامهرمز', en: ''}},
      {id: 37, name: {fa: 'ربیع', en: ''}},
      {id: 38, name: {fa: 'رفیع', en: ''}},
      {id: 39, name: {fa: 'زهره', en: ''}},
      {id: 40, name: {fa: 'سالند', en: ''}},
      {id: 41, name: {fa: 'سرداران', en: ''}},
      {id: 42, name: {fa: 'سردشت', en: ''}},
      {id: 43, name: {fa: 'سوسنگرد', en: ''}},
      {id: 44, name: {fa: 'سیاه منصور', en: ''}},
      {id: 45, name: {fa: 'شادگان', en: ''}},
      {id: 46, name: {fa: 'شاوور', en: ''}},
      {id: 47, name: {fa: 'شرافت', en: ''}},
      {id: 48, name: {fa: 'شوش', en: ''}},
      {id: 49, name: {fa: 'شوشتر', en: ''}},
      {id: 50, name: {fa: 'شیبان', en: ''}},
      {id: 51, name: {fa: 'شیرین شهر', en: ''}},
      {id: 52, name: {fa: 'صفی آباد', en: ''}},
      {id: 53, name: {fa: 'صیدون', en: ''}},
      {id: 54, name: {fa: 'فتح المبین', en: ''}},
      {id: 55, name: {fa: 'قلعه تل', en: ''}},
      {id: 56, name: {fa: 'قلعه خواجه', en: ''}},
      {id: 57, name: {fa: 'کوت عبدالله', en: ''}},
      {id: 58, name: {fa: 'کنعان', en: ''}},
      {id: 59, name: {fa: 'کوت سیدنعیم', en: ''}},
      {id: 60, name: {fa: 'گتوند', en: ''}},
      {id: 61, name: {fa: 'گلگیر', en: ''}},
      {id: 62, name: {fa: 'لالی', en: ''}},
      {id: 63, name: {fa: 'مسجد سلیمان', en: ''}},
      {id: 64, name: {fa: 'مقاومت', en: ''}},
      {id: 65, name: {fa: 'ملاثانی', en: ''}},
      {id: 66, name: {fa: 'منصوریه', en: ''}},
      {id: 67, name: {fa: 'میانرود', en: ''}},
      {id: 68, name: {fa: 'مینوشهر', en: ''}},
      {id: 69, name: {fa: 'میداود', en: ''}},
      {id: 70, name: {fa: 'هفتکل', en: ''}},
      {id: 71, name: {fa: 'هندیجان', en: ''}},
      {id: 72, name: {fa: 'هویزه', en: ''}},
      {id: 73, name: {fa: 'ویس', en: ''}},
  ]},
  { id: 14, name: {fa: "زنجان", en: "Zanjan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آب بر', en: ''}},
      {id: 2, name: {fa: 'ابهر', en: ''}},
      {id: 3, name: {fa: 'ارمغانخانه', en: ''}},
      {id: 4, name: {fa: 'چورزق', en: ''}},
      {id: 5, name: {fa: 'حلب', en: ''}},
      {id: 6, name: {fa: 'خرمدره', en: ''}},
      {id: 7, name: {fa: 'دندی', en: ''}},
      {id: 8, name: {fa: 'زرین آباد', en: ''}},
      {id: 9, name: {fa: 'زرین رود', en: ''}},
      {id: 10, name: {fa: 'زنجان', en: ''}},
      {id: 11, name: {fa: 'سجاس', en: ''}},
      {id: 12, name: {fa: 'سلطانیه', en: ''}},
      {id: 13, name: {fa: 'سهرورد', en: ''}},
      {id: 14, name: {fa: 'صایین قلعه', en: ''}},
      {id: 15, name: {fa: 'قیدار', en: ''}},
      {id: 16, name: {fa: 'کرسف', en: ''}},
      {id: 17, name: {fa: 'گرماب', en: ''}},
      {id: 18, name: {fa: 'ماه نشان', en: ''}},
      {id: 19, name: {fa: 'نوربهار', en: ''}},
      {id: 20, name: {fa: 'نیک پی', en: ''}},
      {id: 21, name: {fa: 'هیدج', en: ''}},
  ]},
  { id: 15, name: {fa: "سمنان", en: "Semnan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آرادان', en: ''}},
      {id: 2, name: {fa: 'امیریه', en: ''}},
      {id: 3, name: {fa: 'ایوانکی', en: ''}},
      {id: 4, name: {fa: 'بسطام', en: ''}},
      {id: 5, name: {fa: 'بیارجمند', en: ''}},
      {id: 6, name: {fa: 'دامغان', en: ''}},
      {id: 7, name: {fa: 'درجزین', en: ''}},
      {id: 8, name: {fa: 'دیباج', en: ''}},
      {id: 9, name: {fa: 'سرخه', en: ''}},
      {id: 10, name: {fa: 'سمنان', en: ''}},
      {id: 11, name: {fa: 'شاهرود', en: ''}},
      {id: 12, name: {fa: 'شهمیرزاد', en: ''}},
      {id: 13, name: {fa: 'کلاته', en: ''}},
      {id: 14, name: {fa: 'کلاته خیج', en: ''}},
      {id: 15, name: {fa: 'کهن آباد', en: ''}},
      {id: 16, name: {fa: 'گرمسار', en: ''}},
      {id: 17, name: {fa: 'مجن', en: ''}},
      {id: 18, name: {fa: 'مهدی شهر', en: ''}},
      {id: 19, name: {fa: 'میامی', en: ''}},
      {id: 20, name: {fa: 'رودیان', en: ''}},
  ]},
  { id: 16, name: {fa: "سیستان و بلوچستان", en: "Sistan and Baluchestan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ادیمی', en: ''}},
      {id: 2, name: {fa: 'اسپکه', en: ''}},
      {id: 3, name: {fa: 'ایرانشهر', en: ''}},
      {id: 4, name: {fa: 'بزمان', en: ''}},
      {id: 5, name: {fa: 'بمپور', en: ''}},
      {id: 6, name: {fa: 'بنت', en: ''}},
      {id: 7, name: {fa: 'بنجار', en: ''}},
      {id: 8, name: {fa: 'پیشین', en: ''}},
      {id: 9, name: {fa: 'جالق', en: ''}},
      {id: 10, name: {fa: 'چابهار', en: ''}},
      {id: 11, name: {fa: 'خاش', en: ''}},
      {id: 12, name: {fa: 'دوست محمد', en: ''}},
      {id: 13, name: {fa: 'راسک', en: ''}},
      {id: 14, name: {fa: 'زابل', en: ''}},
      {id: 15, name: {fa: 'زاهدان', en: ''}},
      {id: 16, name: {fa: 'زهک', en: ''}},
      {id: 17, name: {fa: 'گشت', en: ''}},
      {id: 18, name: {fa: 'سراوان', en: ''}},
      {id: 19, name: {fa: 'سرباز', en: ''}},
      {id: 20, name: {fa: 'سوران', en: ''}},
      {id: 21, name: {fa: 'سیرکان', en: ''}},
      {id: 23, name: {fa: 'هامون شهر', en: ''}},
      {id: 24, name: {fa: 'فنوج', en: ''}},
      {id: 25, name: {fa: 'قصرقند', en: ''}},
      {id: 26, name: {fa: 'کنارک', en: ''}},
      {id: 27, name: {fa: 'گلمورتی', en: ''}},
      {id: 28, name: {fa: 'محمدآباد', en: ''}},
      {id: 29, name: {fa: 'محمدی', en: ''}},
      {id: 30, name: {fa: 'مهرستان', en: ''}},
      {id: 31, name: {fa: 'میرجاوه', en: ''}},
      {id: 32, name: {fa: 'نصرت آباد', en: ''}},
      {id: 33, name: {fa: 'نگور', en: ''}},
      {id: 34, name: {fa: 'نوک آباد', en: ''}},
      {id: 35, name: {fa: 'نیک شهر', en: ''}},
  ]},
  { id: 17, name: {fa: "فارس", en: "Fars"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آباده', en: ''}},
      {id: 2, name: {fa: 'ارد', en: ''}},
      {id: 3, name: {fa: 'اردکان', en: ''}},
      {id: 4, name: {fa: 'ارسنجان', en: ''}},
      {id: 5, name: {fa: 'استهبان', en: ''}},
      {id: 6, name: {fa: 'اسیر', en: ''}},
      {id: 7, name: {fa: 'اشکنان', en: ''}},
      {id: 8, name: {fa: 'افرز', en: ''}},
      {id: 9, name: {fa: 'اقلید', en: ''}},
      {id: 10, name: {fa: 'امام شهر', en: ''}},
      {id: 11, name: {fa: 'اهل', en: ''}},
      {id: 12, name: {fa: 'اوز', en: ''}},
      {id: 13, name: {fa: 'ایج', en: ''}},
      {id: 14, name: {fa: 'ایزدخواست', en: ''}},
      {id: 15, name: {fa: 'باب انار', en: ''}},
      {id: 16, name: {fa: 'بالاده', en: ''}},
      {id: 17, name: {fa: 'بنارویه', en: ''}},
      {id: 18, name: {fa: 'بهمن', en: ''}},
      {id: 19, name: {fa: 'بیرم', en: ''}},
      {id: 20, name: {fa: 'بیضا', en: ''}},
      {id: 21, name: {fa: 'جنت شهر', en: ''}},
      {id: 23, name: {fa: 'جهرم', en: ''}},
      {id: 24, name: {fa: 'جویم', en: ''}},
      {id: 25, name: {fa: 'حاجی آباد', en: ''}},
      {id: 26, name: {fa: 'خانمین', en: ''}},
      {id: 27, name: {fa: 'خاوران', en: ''}},
      {id: 28, name: {fa: 'خرامه', en: ''}},
      {id: 29, name: {fa: 'خشت', en: ''}},
      {id: 30, name: {fa: 'خنج', en: ''}},
      {id: 31, name: {fa: 'خور', en: ''}},
      {id: 32, name: {fa: 'خومه زار', en: ''}},
      {id: 33, name: {fa: 'داراب', en: ''}},
      {id: 34, name: {fa: 'داریان', en: ''}},
      {id: 35, name: {fa: 'دوبرجی', en: ''}},
      {id: 36, name: {fa: 'دوزه', en: ''}},
      {id: 37, name: {fa: 'دهرم', en: ''}},
      {id: 38, name: {fa: 'رامجرد', en: ''}},
      {id: 39, name: {fa: 'رونیز', en: ''}},
      {id: 40, name: {fa: 'زاهدشهر', en: ''}},
      {id: 41, name: {fa: 'زرقان', en: ''}},
      {id: 42, name: {fa: 'سده', en: ''}},
      {id: 43, name: {fa: 'سروستان', en: ''}},
      {id: 44, name: {fa: 'سلطان شهر', en: ''}},
      {id: 45, name: {fa: 'سعادت شهر', en: ''}},
      {id: 46, name: {fa: 'سورمق', en: ''}},
      {id: 47, name: {fa: 'سوریان', en: ''}},
      {id: 48, name: {fa: 'سیدان', en: ''}},
      {id: 49, name: {fa: 'سیوند', en: ''}},
      {id: 50, name: {fa: 'ششده', en: ''}},
      {id: 51, name: {fa: 'شهرپیر', en: ''}},
      {id: 52, name: {fa: 'شیراز', en: ''}},
      {id: 53, name: {fa: 'صغاد', en: ''}},
      {id: 54, name: {fa: 'صفاشهر', en: ''}},
      {id: 55, name: {fa: 'علامرودشت', en: ''}},
      {id: 56, name: {fa: 'فاروق', en: ''}},
      {id: 57, name: {fa: 'فراشبند', en: ''}},
      {id: 58, name: {fa: 'فسا', en: ''}},
      {id: 59, name: {fa: 'فیروزآباد', en: ''}},
      {id: 60, name: {fa: 'قائمیه', en: ''}},
      {id: 61, name: {fa: 'قادرآباد', en: ''}},
      {id: 62, name: {fa: 'قطب آباد', en: ''}},
      {id: 63, name: {fa: 'قیر', en: ''}},
      {id: 64, name: {fa: 'کارزین', en: ''}},
      {id: 65, name: {fa: 'کازرون', en: ''}},
      {id: 66, name: {fa: 'کامفیروز', en: ''}},
      {id: 67, name: {fa: 'کره‌ای', en: ''}},
      {id: 68, name: {fa: 'کنارتخته', en: ''}},
      {id: 69, name: {fa: 'کوار', en: ''}},
      {id: 70, name: {fa: 'کوپن', en: ''}},
      {id: 71, name: {fa: 'کوهنجان', en: ''}},
      {id: 72, name: {fa: 'گراش', en: ''}},
      {id: 73, name: {fa: 'گله‌دار', en: ''}},
      {id: 74, name: {fa: 'لار', en: ''}},
      {id: 75, name: {fa: 'لامرد', en: ''}},
      {id: 76, name: {fa: 'لپوئی', en: ''}},
      {id: 77, name: {fa: 'لطیفی', en: ''}},
      {id: 78, name: {fa: 'مادرسلیمان', en: ''}},
      {id: 79, name: {fa: 'مبارک آباد', en: ''}},
      {id: 70, name: {fa: 'مرودشت', en: ''}},
      {id: 71, name: {fa: 'مشکان', en: ''}},
      {id: 72, name: {fa: 'مصیری', en: ''}},
      {id: 73, name: {fa: 'مهر', en: ''}},
      {id: 74, name: {fa: 'میمند', en: ''}},
      {id: 75, name: {fa: 'نوجین', en: ''}},
      {id: 76, name: {fa: 'نودان', en: ''}},
      {id: 77, name: {fa: 'نورآباد', en: ''}},
      {id: 78, name: {fa: 'نی‌ریز', en: ''}},
      {id: 79, name: {fa: 'وراوی', en: ''}},
      {id: 80, name: {fa: 'هماشهر', en: ''}},
  ]},
  { id: 18, name: {fa: "قزوین", en: "Qazvin"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آبگرم', en: ''}},
      {id: 2, name: {fa: 'آبیک', en: ''}},
      {id: 3, name: {fa: 'آوج', en: ''}},
      {id: 4, name: {fa: 'ارداق', en: ''}},
      {id: 5, name: {fa: 'اسفرورین', en: ''}},
      {id: 6, name: {fa: 'اقبالیه', en: ''}},
      {id: 7, name: {fa: 'الوند', en: ''}},
      {id: 8, name: {fa: 'بوئین زهرا', en: ''}},
      {id: 9, name: {fa: 'بیدستان', en: ''}},
      {id: 10, name: {fa: 'تاکستان', en: ''}},
      {id: 11, name: {fa: 'خاکعلی', en: ''}},
      {id: 12, name: {fa: 'خرمدشت', en: ''}},
      {id: 13, name: {fa: 'دانسفهان', en: ''}},
      {id: 14, name: {fa: 'رازمیان', en: ''}},
      {id: 15, name: {fa: 'سگزآباد', en: ''}},
      {id: 16, name: {fa: 'سیردان', en: ''}},
      {id: 17, name: {fa: 'شال', en: ''}},
      {id: 18, name: {fa: 'شریفیه', en: ''}},
      {id: 19, name: {fa: 'ضیاء آباد', en: ''}},
      {id: 20, name: {fa: 'قزوین', en: ''}},
      {id: 21, name: {fa: 'کوهین', en: ''}},
      {id: 23, name: {fa: 'محمدیه', en: ''}},
      {id: 24, name: {fa: 'محمودآباد نمونه', en: ''}},
      {id: 25, name: {fa: 'معلم کلایه', en: ''}},
      {id: 26, name: {fa: 'نرجه', en: ''}},
  ]},
  { id: 19, name: {fa: "قم", en: "Qom"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'جعفریه', en: ''}},
      {id: 2, name: {fa: 'دستجرد', en: ''}},
      {id: 3, name: {fa: 'سلفچگان', en: ''}},
      {id: 4, name: {fa: 'قم', en: ''}},
      {id: 5, name: {fa: 'قنوات', en: ''}},
      {id: 6, name: {fa: 'کهک', en: ''}},
  ]},
  { id: 20, name: {fa: "کردستان", en: "Kurdistan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آرمرده', en: ''}},
      {id: 2, name: {fa: 'اورامان', en: ''}},
      {id: 3, name: {fa: 'بابارشانی', en: ''}},
      {id: 4, name: {fa: 'بانه', en: ''}},
      {id: 5, name: {fa: 'بلبان آباد', en: ''}},
      {id: 6, name: {fa: 'بویین سفلی', en: ''}},
      {id: 7, name: {fa: 'بیجار', en: ''}},
      {id: 8, name: {fa: 'پیرتاج', en: ''}},
      {id: 9, name: {fa: 'توپ آغاج', en: ''}},
      {id: 10, name: {fa: 'چناره', en: ''}},
      {id: 11, name: {fa: 'دزج', en: ''}},
      {id: 12, name: {fa: 'دلبران', en: ''}},
      {id: 13, name: {fa: 'دهگلان', en: ''}},
      {id: 14, name: {fa: 'دیواندره', en: ''}},
      {id: 15, name: {fa: 'زرینه', en: ''}},
      {id: 16, name: {fa: 'سروآباد', en: ''}},
      {id: 17, name: {fa: 'سریش آباد', en: ''}},
      {id: 18, name: {fa: 'سقز', en: ''}},
      {id: 19, name: {fa: 'سنندج', en: ''}},
      {id: 20, name: {fa: 'شویشه', en: ''}},
      {id: 21, name: {fa: 'صاحب', en: ''}},
      {id: 23, name: {fa: 'قروه', en: ''}},
      {id: 24, name: {fa: 'کامیاران', en: ''}},
      {id: 25, name: {fa: 'کانی دینار', en: ''}},
      {id: 26, name: {fa: 'کانی سور', en: ''}},
      {id: 27, name: {fa: 'مریوان', en: ''}},
      {id: 28, name: {fa: 'موچش', en: ''}},
      {id: 29, name: {fa: 'یاسوکند', en: ''}},
  ]},
  { id: 21, name: {fa: "کرمان", en: "Kerman"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'اختیار آباد', en: ''}},
      {id: 2, name: {fa: 'ارزوئیه', en: ''}},
      {id: 3, name: {fa: 'امین شهر', en: ''}},
      {id: 4, name: {fa: 'انار', en: ''}},
      {id: 5, name: {fa: 'اندوهجرد', en: ''}},
      {id: 6, name: {fa: 'باغین', en: ''}},
      {id: 7, name: {fa: 'بافت', en: ''}},
      {id: 8, name: {fa: 'بردسیر', en: ''}},
      {id: 9, name: {fa: 'بروات', en: ''}},
      {id: 10, name: {fa: 'بزنجان', en: ''}},
      {id: 11, name: {fa: 'بم', en: ''}},
      {id: 12, name: {fa: 'بهرمان', en: ''}},
      {id: 13, name: {fa: 'پاریز', en: ''}},
      {id: 14, name: {fa: 'جبال بارز', en: ''}},
      {id: 15, name: {fa: 'جوزم', en: ''}},
      {id: 16, name: {fa: 'جوپار', en: ''}},
      {id: 17, name: {fa: 'جیرفت', en: ''}},
      {id: 18, name: {fa: 'چترود', en: ''}},
      {id: 19, name: {fa: 'خاتون آباد', en: ''}},
      {id: 20, name: {fa: 'خانوک', en: ''}},
      {id: 21, name: {fa: 'خرسند', en: ''}},
      {id: 23, name: {fa: 'خواجو شهر', en: ''}},
      {id: 24, name: {fa: 'درب بهشت', en: ''}},
      {id: 25, name: {fa: 'دهج', en: ''}},
      {id: 26, name: {fa: 'رابر', en: ''}},
      {id: 27, name: {fa: 'راور', en: ''}},
      {id: 28, name: {fa: 'راین', en: ''}},
      {id: 29, name: {fa: 'رفسنجان', en: ''}},
      {id: 30, name: {fa: 'رودبار', en: ''}},
      {id: 31, name: {fa: 'ریحان شهر', en: ''}},
      {id: 32, name: {fa: 'زرند', en: ''}},
      {id: 33, name: {fa: 'زنگی آباد', en: ''}},
      {id: 34, name: {fa: 'زید آباد', en: ''}},
      {id: 35, name: {fa: 'سیرجان', en: ''}},
      {id: 36, name: {fa: 'شهداد', en: ''}},
      {id: 37, name: {fa: 'شهربابک', en: ''}},
      {id: 38, name: {fa: 'صفائیه', en: ''}},
      {id: 39, name: {fa: 'عنبرآباد', en: ''}},
      {id: 40, name: {fa: 'فاریاب', en: ''}},
      {id: 41, name: {fa: 'فهرج', en: ''}},
      {id: 42, name: {fa: 'قلعه گنج', en: ''}},
      {id: 43, name: {fa: 'کاظم آباد', en: ''}},
      {id: 44, name: {fa: 'کرمان', en: ''}},
      {id: 45, name: {fa: 'کشکوئیه', en: ''}},
      {id: 46, name: {fa: 'کهنوج', en: ''}},
      {id: 47, name: {fa: 'کوهبنان', en: ''}},
      {id: 48, name: {fa: 'لاله‌زار', en: ''}},
      {id: 49, name: {fa: 'ماهان', en: ''}},
      {id: 50, name: {fa: 'محمدآباد', en: ''}},
      {id: 51, name: {fa: 'محی آباد', en: ''}},
      {id: 52, name: {fa: 'مردهک', en: ''}},
      {id: 53, name: {fa: 'مس سرچشمه', en: ''}},
      {id: 54, name: {fa: 'منوجان', en: ''}},
      {id: 55, name: {fa: 'نجف شهر', en: ''}},
      {id: 56, name: {fa: 'نرماشیر', en: ''}},
      {id: 57, name: {fa: 'نظام شهر', en: ''}},
      {id: 58, name: {fa: 'نگار', en: ''}},
      {id: 59, name: {fa: 'نودژ', en: ''}},
      {id: 60, name: {fa: 'هجدک', en: ''}},
      {id: 61, name: {fa: 'هماشهر', en: ''}},
      {id: 62, name: {fa: 'هنزا', en: ''}},
      {id: 63, name: {fa: 'یزدان شهر', en: ''}},
  ]},
  { id: 22, name: {fa: "کرمانشاه", en: "Kermanshah"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ازگله', en: ''}},
      {id: 2, name: {fa: 'اسلام آباد غرب', en: ''}},
      {id: 3, name: {fa: 'بانه‌وره', en: ''}},
      {id: 4, name: {fa: 'باینگان', en: ''}},
      {id: 5, name: {fa: 'بیستون', en: ''}},
      {id: 6, name: {fa: 'پاوه', en: ''}},
      {id: 7, name: {fa: 'تازه آباد', en: ''}},
      {id: 8, name: {fa: 'جوانرود', en: ''}},
      {id: 9, name: {fa: 'حمیل', en: ''}},
      {id: 10, name: {fa: 'رباط', en: ''}},
      {id: 11, name: {fa: 'روانسر', en: ''}},
      {id: 12, name: {fa: 'ریجاب', en: ''}},
      {id: 13, name: {fa: 'سرپل ذهاب', en: ''}},
      {id: 14, name: {fa: 'سرمست', en: ''}},
      {id: 15, name: {fa: 'سطر', en: ''}},
      {id: 16, name: {fa: 'سنقر', en: ''}},
      {id: 17, name: {fa: 'سومار', en: ''}},
      {id: 18, name: {fa: 'شاهو', en: ''}},
      {id: 19, name: {fa: 'صحنه', en: ''}},
      {id: 20, name: {fa: 'قصر شیرین', en: ''}},
      {id: 21, name: {fa: 'کرمانشاه', en: ''}},
      {id: 23, name: {fa: 'کرند غرب', en: ''}},
      {id: 24, name: {fa: 'کنگاور', en: ''}},
      {id: 25, name: {fa: 'کوزران', en: ''}},
      {id: 36, name: {fa: 'گهواره', en: ''}},
      {id: 37, name: {fa: 'گودین', en: ''}},
      {id: 38, name: {fa: 'گیلانغرب', en: ''}},
      {id: 39, name: {fa: 'میان راهان', en: ''}},
      {id: 40, name: {fa: 'نودشه', en: ''}},
      {id: 41, name: {fa: 'نوسود', en: ''}},
      {id: 43, name: {fa: 'هرسین', en: ''}},
      {id: 44, name: {fa: 'هلشی', en: ''}},
  ]},
  { id: 23, name: {fa: "کهگیلویه و بویراحمد", en: "Kohgiluyeh and Boyer-Ahmad"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'باشت', en: ''}},
      {id: 2, name: {fa: 'پاتاوه', en: ''}},
      {id: 3, name: {fa: 'چرام', en: ''}},
      {id: 4, name: {fa: 'چیتاب', en: ''}},
      {id: 5, name: {fa: 'دهدشت', en: ''}},
      {id: 6, name: {fa: 'دوگنبدان', en: ''}},
      {id: 7, name: {fa: 'دیشموک', en: ''}},
      {id: 8, name: {fa: 'سوق', en: ''}},
      {id: 9, name: {fa: 'سی‌سخت', en: ''}},
      {id: 10, name: {fa: 'سرفاریاب', en: ''}},
      {id: 11, name: {fa: 'قلعه رئیسی', en: ''}},
      {id: 12, name: {fa: 'گراب سفلی', en: ''}},
      {id: 13, name: {fa: 'لنده', en: ''}},
      {id: 14, name: {fa: 'لیکک', en: ''}},
      {id: 15, name: {fa: 'مادوان', en: ''}},
      {id: 16, name: {fa: 'مارگون', en: ''}},
      {id: 17, name: {fa: 'یاسوج', en: ''}},
  ]},
  { id: 24, name: {fa: "گلستان", en: "Golestan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آزادشهر', en: ''}},
      {id: 2, name: {fa: 'آق‌قلا', en: ''}},
      {id: 3, name: {fa: 'انبار آلوم', en: ''}},
      {id: 4, name: {fa: 'اینچه برون', en: ''}},
      {id: 5, name: {fa: 'بندر ترکمن', en: ''}},
      {id: 6, name: {fa: 'بندر گز', en: ''}},
      {id: 7, name: {fa: 'خان ببین', en: ''}},
      {id: 8, name: {fa: 'دلند', en: ''}},
      {id: 9, name: {fa: 'رامیان', en: ''}},
      {id: 10, name: {fa: 'سرخنکلاته', en: ''}},
      {id: 11, name: {fa: 'سیمین شهر', en: ''}},
      {id: 12, name: {fa: 'علی آباد', en: ''}},
      {id: 13, name: {fa: 'فاضل آباد', en: ''}},
      {id: 14, name: {fa: 'فراغی', en: ''}},
      {id: 15, name: {fa: 'کردکوی', en: ''}},
      {id: 16, name: {fa: 'کلاله', en: ''}},
      {id: 17, name: {fa: 'گالیکش', en: ''}},
      {id: 18, name: {fa: 'گرگان', en: ''}},
      {id: 19, name: {fa: 'گمیشان', en: ''}},
      {id: 20, name: {fa: 'گنبد کاووس', en: ''}},
      {id: 21, name: {fa: 'مراوه تپه', en: ''}},
      {id: 23, name: {fa: 'مینودشت', en: ''}},
      {id: 24, name: {fa: 'نگین شهر', en: ''}},
      {id: 25, name: {fa: 'نوده خاندوز', en: ''}},
      {id: 26, name: {fa: 'نوکنده', en: ''}},
  ]},
  { id: 25, name: {fa: "گیلان", en: "Gilan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آستارا', en: ''}},
      {id: 2, name: {fa: 'آستانه اشرفیه', en: ''}},
      {id: 3, name: {fa: 'احمدسرگوراب', en: ''}},
      {id: 4, name: {fa: 'اسالم', en: ''}},
      {id: 5, name: {fa: 'اطاقور', en: ''}},
      {id: 6, name: {fa: 'املش', en: ''}},
      {id: 7, name: {fa: 'بازارجمعه', en: ''}},
      {id: 8, name: {fa: 'بره سر', en: ''}},
      {id: 9, name: {fa: 'بندر انزلی', en: ''}},
      {id: 10, name: {fa: 'پره سر', en: ''}},
      {id: 11, name: {fa: 'توتکابن', en: ''}},
      {id: 12, name: {fa: 'جیرنده', en: ''}},
      {id: 13, name: {fa: 'چابکسر', en: ''}},
      {id: 14, name: {fa: 'چاف و چمخاله', en: ''}},
      {id: 15, name: {fa: 'چوبر', en: ''}},
      {id: 16, name: {fa: 'حویق', en: ''}},
      {id: 17, name: {fa: 'خشکبیجار', en: ''}},
      {id: 18, name: {fa: 'خمام', en: ''}},
      {id: 19, name: {fa: 'دیلمان', en: ''}},
      {id: 20, name: {fa: 'رانکوه', en: ''}},
      {id: 21, name: {fa: 'رحیم آباد', en: ''}},
      {id: 23, name: {fa: 'رستم آباد', en: ''}},
      {id: 24, name: {fa: 'رشت', en: ''}},
      {id: 25, name: {fa: 'رضوانشهر', en: ''}},
      {id: 26, name: {fa: 'رودبار', en: ''}},
      {id: 27, name: {fa: 'رودسر', en: ''}},
      {id: 28, name: {fa: 'رودبنه', en: ''}},
      {id: 29, name: {fa: 'سنگر', en: ''}},
      {id: 30, name: {fa: 'سیاهکل', en: ''}},
      {id: 31, name: {fa: 'شفت', en: ''}},
      {id: 32, name: {fa: 'شلمان', en: ''}},
      {id: 33, name: {fa: 'صومعه سرا', en: ''}},
      {id: 34, name: {fa: 'فومن', en: ''}},
      {id: 35, name: {fa: 'کلاچای', en: ''}},
      {id: 36, name: {fa: 'کوچصفهان', en: ''}},
      {id: 37, name: {fa: 'کومله', en: ''}},
      {id: 38, name: {fa: 'کیاشهر', en: ''}},
      {id: 39, name: {fa: 'گوراب زرمیخ', en: ''}},
      {id: 40, name: {fa: 'لاهیجان', en: ''}},
      {id: 41, name: {fa: 'لشت نشا', en: ''}},
      {id: 42, name: {fa: 'لنگرود', en: ''}},
      {id: 43, name: {fa: 'لوشان', en: ''}},
      {id: 44, name: {fa: 'لوندویل', en: ''}},
      {id: 45, name: {fa: 'لیسار', en: ''}},
      {id: 46, name: {fa: 'ماسال', en: ''}},
      {id: 47, name: {fa: 'ماسوله', en: ''}},
      {id: 48, name: {fa: 'ماکلوان', en: ''}},
      {id: 49, name: {fa: 'مرجغل', en: ''}},
      {id: 40, name: {fa: 'منجیل', en: ''}},
      {id: 41, name: {fa: 'واجارگاه', en: ''}},
      {id: 42, name: {fa: 'هشتپر', en: ''}},
  ]},
  { id: 26, name: {fa: "لرستان", en: "Lorestan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ازنا', en: ''}},
      {id: 2, name: {fa: 'اشترینان', en: ''}},
      {id: 3, name: {fa: 'الشتر', en: ''}},
      {id: 4, name: {fa: 'الیگودرز', en: ''}},
      {id: 5, name: {fa: 'بروجرد', en: ''}},
      {id: 6, name: {fa: 'بیرانشهر', en: ''}},
      {id: 7, name: {fa: 'پل دختر', en: ''}},
      {id: 8, name: {fa: 'چالانچولان', en: ''}},
      {id: 9, name: {fa: 'چقابل', en: ''}},
      {id: 10, name: {fa: 'خرم آباد', en: ''}},
      {id: 11, name: {fa: 'درب گنبد', en: ''}},
      {id: 12, name: {fa: 'دورود', en: ''}},
      {id: 13, name: {fa: 'زاغه', en: ''}},
      {id: 14, name: {fa: 'سپیددشت', en: ''}},
      {id: 15, name: {fa: 'سراب دوره', en: ''}},
      {id: 16, name: {fa: 'شول آباد', en: ''}},
      {id: 17, name: {fa: 'فیروز آباد', en: ''}},
      {id: 18, name: {fa: 'کونانی', en: ''}},
      {id: 19, name: {fa: 'کوهدشت', en: ''}},
      {id: 20, name: {fa: 'گراب', en: ''}},
      {id: 21, name: {fa: 'معمولان', en: ''}},
      {id: 23, name: {fa: 'مومن آباد', en: ''}},
      {id: 24, name: {fa: 'نورآباد', en: ''}},
  ]},
  { id: 27, name: {fa: "مازندران", en: "Mazandaran"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آلاشت', en: ''}},
      {id: 2, name: {fa: 'امامزاده عبدالله', en: ''}},
      {id: 3, name: {fa: 'آمل', en: ''}},
      {id: 4, name: {fa: 'امیرکلا', en: ''}},
      {id: 5, name: {fa: 'ایزدشهر', en: ''}},
      {id: 6, name: {fa: 'بابل', en: ''}},
      {id: 7, name: {fa: 'بابلسر', en: ''}},
      {id: 8, name: {fa: 'بلده', en: ''}},
      {id: 9, name: {fa: 'بهشهر', en: ''}},
      {id: 10, name: {fa: 'بهنمیر', en: ''}},
      {id: 11, name: {fa: 'پل سفید', en: ''}},
      {id: 12, name: {fa: 'تنکابن', en: ''}},
      {id: 13, name: {fa: 'جویبار', en: ''}},
      {id: 14, name: {fa: 'چالوس', en: ''}},
      {id: 15, name: {fa: 'چمستان', en: ''}},
      {id: 16, name: {fa: 'خرم آباد', en: ''}},
      {id: 17, name: {fa: 'خلیل شهر', en: ''}},
      {id: 18, name: {fa: 'خوش رودپی', en: ''}},
      {id: 19, name: {fa: 'دابودشت', en: ''}},
      {id: 20, name: {fa: 'رامسر', en: ''}},
      {id: 21, name: {fa: 'رستمکلا', en: ''}},
      {id: 23, name: {fa: 'رویان', en: ''}},
      {id: 24, name: {fa: 'رینه', en: ''}},
      {id: 25, name: {fa: 'زرگرمحله', en: ''}},
      {id: 26, name: {fa: 'زیرآب', en: ''}},
      {id: 27, name: {fa: 'ساری', en: ''}},
      {id: 28, name: {fa: 'سرخ رود', en: ''}},
      {id: 29, name: {fa: 'سلمان شهر', en: ''}},
      {id: 30, name: {fa: 'سورک', en: ''}},
      {id: 31, name: {fa: 'شیرگاه', en: ''}},
      {id: 32, name: {fa: 'شیرود', en: ''}},
      {id: 33, name: {fa: 'عباس آباد', en: ''}},
      {id: 34, name: {fa: 'فریدون کنار', en: ''}},
      {id: 35, name: {fa: 'فریم', en: ''}},
      {id: 36, name: {fa: 'قائم شهر', en: ''}},
      {id: 37, name: {fa: 'کتالم و سادات شهر', en: ''}},
      {id: 38, name: {fa: 'کلارآباد', en: ''}},
      {id: 39, name: {fa: 'کلاردشت', en: ''}},
      {id: 40, name: {fa: 'کوهی خیل', en: ''}},
      {id: 41, name: {fa: 'کیاسر', en: ''}},
      {id: 42, name: {fa: 'کیاکلا', en: ''}},
      {id: 43, name: {fa: 'گزنک', en: ''}},
      {id: 44, name: {fa: 'گلوگاه', en: ''}},
      {id: 45, name: {fa: 'گلوگاه بابل', en: ''}},
      {id: 46, name: {fa: 'گتاب', en: ''}},
      {id: 47, name: {fa: 'محمود آباد', en: ''}},
      {id: 48, name: {fa: 'مرزن آباد', en: ''}},
      {id: 49, name: {fa: 'مرزیکلا', en: ''}},
      {id: 40, name: {fa: 'نشتارود', en: ''}},
      {id: 41, name: {fa: 'نکا', en: ''}},
      {id: 42, name: {fa: 'نور', en: ''}},
      {id: 43, name: {fa: 'نوشهر', en: ''}},
      {id: 44, name: {fa: 'هادی شهر', en: ''}},
  ]},
  { id: 28, name: {fa: "مرکزی", en: "Markazi"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'آستانه', en: ''}},
      {id: 2, name: {fa: 'آشتیان', en: ''}},
      {id: 3, name: {fa: 'آوه', en: ''}},
      {id: 4, name: {fa: 'اراک', en: ''}},
      {id: 5, name: {fa: 'پرندک', en: ''}},
      {id: 6, name: {fa: 'تفرش', en: ''}},
      {id: 7, name: {fa: 'توره', en: ''}},
      {id: 8, name: {fa: 'جاورسیان', en: ''}},
      {id: 9, name: {fa: 'خشکرود', en: ''}},
      {id: 10, name: {fa: 'خمین', en: ''}},
      {id: 11, name: {fa: 'خنداب', en: ''}},
      {id: 12, name: {fa: 'خنجین', en: ''}},
      {id: 13, name: {fa: 'داوود آباد', en: ''}},
      {id: 14, name: {fa: 'دلیجان', en: ''}},
      {id: 15, name: {fa: 'رازقان', en: ''}},
      {id: 16, name: {fa: 'زاویه', en: ''}},
      {id: 17, name: {fa: 'ساروق', en: ''}},
      {id: 18, name: {fa: 'ساوه', en: ''}},
      {id: 19, name: {fa: 'شازند', en: ''}},
      {id: 20, name: {fa: 'شهباز', en: ''}},
      {id: 21, name: {fa: 'غرق آباد', en: ''}},
      {id: 23, name: {fa: 'فرمهین', en: ''}},
      {id: 24, name: {fa: 'قورچی باشی', en: ''}},
      {id: 25, name: {fa: 'کارچان', en: ''}},
      {id: 26, name: {fa: 'کمیجان', en: ''}},
      {id: 27, name: {fa: 'مأمونیه', en: ''}},
      {id: 28, name: {fa: 'محلات', en: ''}},
      {id: 29, name: {fa: 'مهاجران', en: ''}},
      {id: 30, name: {fa: 'میلاجرد', en: ''}},
      {id: 31, name: {fa: 'نراق', en: ''}},
      {id: 32, name: {fa: 'نوبران', en: ''}},
      {id: 33, name: {fa: 'نیم‌ور', en: ''}},
      {id: 34, name: {fa: 'هندودر', en: ''}},
  ]},
  { id: 29, name: {fa: "هرمزگان", en: "Hormozgān"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'بندر چارک', en: ''}},
      {id: 2, name: {fa: 'بندر خمیر', en: ''}},
      {id: 3, name: {fa: 'بندر عباس', en: ''}},
      {id: 4, name: {fa: 'بندر لنگه', en: ''}},
      {id: 5, name: {fa: 'پارسیان', en: ''}},
      {id: 6, name: {fa: 'تازیان پایین', en: ''}},
      {id: 7, name: {fa: 'تیرور', en: ''}},
      {id: 8, name: {fa: 'جاسک', en: ''}},
      {id: 9, name: {fa: 'جناح', en: ''}},
      {id: 10, name: {fa: 'حاجی آباد', en: ''}},
      {id: 11, name: {fa: 'درگهان', en: ''}},
      {id: 12, name: {fa: 'دهبارز', en: ''}},
      {id: 13, name: {fa: 'رویدر', en: ''}},
      {id: 14, name: {fa: 'زیارت علی', en: ''}},
      {id: 15, name: {fa: 'سردشت', en: ''}},
      {id: 16, name: {fa: 'سندرک', en: ''}},
      {id: 17, name: {fa: 'سوزا', en: ''}},
      {id: 18, name: {fa: 'سیریک', en: ''}},
      {id: 19, name: {fa: 'فارغان', en: ''}},
      {id: 20, name: {fa: 'فین', en: ''}},
      {id: 21, name: {fa: 'قشم', en: ''}},
      {id: 23, name: {fa: 'کنگ', en: ''}},
      {id: 24, name: {fa: 'کوخردهرنگ', en: ''}},
      {id: 25, name: {fa: 'کوهستک', en: ''}},
      {id: 26, name: {fa: 'کیش', en: ''}},
      {id: 27, name: {fa: 'لمزان', en: ''}},
      {id: 28, name: {fa: 'هرمز', en: ''}},
      {id: 29, name: {fa: 'هشت بندی', en: ''}},
      {id: 30, name: {fa: 'میناب', en: ''}},
  ]},
  { id: 30, name: {fa: "همدان", en: "Hamadan"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ازندریان', en: ''}},
      {id: 2, name: {fa: 'اسدآباد', en: ''}},
      {id: 3, name: {fa: 'برزول', en: ''}},
      {id: 4, name: {fa: 'بهار', en: ''}},
      {id: 5, name: {fa: 'تویسرکان', en: ''}},
      {id: 6, name: {fa: 'جورقان', en: ''}},
      {id: 7, name: {fa: 'جوکار', en: ''}},
      {id: 8, name: {fa: 'دمق', en: ''}},
      {id: 9, name: {fa: 'رزن', en: ''}},
      {id: 10, name: {fa: 'زنگنه', en: ''}},
      {id: 11, name: {fa: 'سامن', en: ''}},
      {id: 12, name: {fa: 'سرکان', en: ''}},
      {id: 13, name: {fa: 'شیرین‌سو', en: ''}},
      {id: 14, name: {fa: 'صالح آباد', en: ''}},
      {id: 15, name: {fa: 'فامنین', en: ''}},
      {id: 16, name: {fa: 'فرسفج', en: ''}},
      {id: 17, name: {fa: 'فیروزان', en: ''}},
      {id: 18, name: {fa: 'قروه درجزین', en: ''}},
      {id: 19, name: {fa: 'قهاوند', en: ''}},
      {id: 20, name: {fa: 'کبودرآهنگ', en: ''}},
      {id: 21, name: {fa: 'گل تپه', en: ''}},
      {id: 23, name: {fa: 'گیان', en: ''}},
      {id: 24, name: {fa: 'لالجین', en: ''}},
      {id: 25, name: {fa: 'مریانج', en: ''}},
      {id: 26, name: {fa: 'ملایر', en: ''}},
      {id: 27, name: {fa: 'مهاجران', en: ''}},
      {id: 28, name: {fa: 'نهاوند', en: ''}},
      {id: 29, name: {fa: 'همدان', en: ''}},
  ]},
  { id: 31, name: {fa: "یزد", en: "Yazd"},
    citiesNames: [
      {id: 0, name: {fa: '---', en: '---'}},
      {id: 1, name: {fa: 'ابرکوه', en: ''}},
      {id: 2, name: {fa: 'احمد آباد', en: ''}},
      {id: 3, name: {fa: 'اردکان', en: ''}},
      {id: 4, name: {fa: 'اشکذر', en: ''}},
      {id: 5, name: {fa: 'بافق', en: ''}},
      {id: 6, name: {fa: 'بفرئیه', en: ''}},
      {id: 7, name: {fa: 'بهاباد', en: ''}},
      {id: 8, name: {fa: 'تفت', en: ''}},
      {id: 9, name: {fa: 'حمیدیا', en: ''}},
      {id: 10, name: {fa: 'خضرآباد', en: ''}},
      {id: 11, name: {fa: 'زارچ', en: ''}},
      {id: 12, name: {fa: 'شاهدیه', en: ''}},
      {id: 13, name: {fa: 'عقدا', en: ''}},
      {id: 14, name: {fa: 'مروست', en: ''}},
      {id: 15, name: {fa: 'مهردشت', en: ''}},
      {id: 16, name: {fa: 'مهریز', en: ''}},
      {id: 17, name: {fa: 'میبد', en: ''}},
      {id: 18, name: {fa: 'ندوشن', en: ''}},
      {id: 19, name: {fa: 'نیر', en: ''}},
      {id: 20, name: {fa: 'هرات', en: ''}},
      {id: 21, name: {fa: 'یزد', en: ''}},
  ]},
]
