import { language, ln, dir } from './language'

export const provinces = [
  { id: 0, name: {fa: '---', en: '---'}},
  { id: 1, name: {fa: "آذربایجان شرقی", en: "Azerbaijan, East"}},
  { id: 2, name: {fa: "آذربایجان غربی", en: "Azerbaijan, West"}},
  { id: 3, name: {fa: "اردبیل", en: "Ardabil"}},
  { id: 4, name: {fa: "اصفهان", en: "Isfahan"}},
  { id: 5, name: {fa: "البرز", en: "Alborz"}},
  { id: 6, name: {fa: "ایلام", en: "Ilam"}},
  { id: 7, name: {fa: "بوشهر", en: "Bushehr"}},
  { id: 8, name: {fa: "تهران", en: "Tehran"}},
  { id: 9, name: {fa: "چهارمحال و بختیاری", en: "Chahar Mahaal and Bakhtiari"}},
  { id: 10, name: {fa: "خراسان جنوبی", en: "Khorasan, South"}},
  { id: 11, name: {fa: "خراسان رضوی", en: "Khorasan, Razavi"}},
  { id: 12, name: {fa: "خراسان شمالی", en: "Khorasan, North"}},
  { id: 13, name: {fa: "خوزستان", en: "Khuzestan"}},
  { id: 14, name: {fa: "زنجان", en: "Zanjan"}},
  { id: 15, name: {fa: "سمنان", en: "Semnan"}},
  { id: 16, name: {fa: "سیستان و بلوچستان", en: "Sistan and Baluchestan"}},
  { id: 17, name: {fa: "فارس", en: "Fars"}},
  { id: 18, name: {fa: "قزوین", en: "Qazvin"}},
  { id: 19, name: {fa: "قم", en: "Qom"}},
  { id: 20, name: {fa: "کردستان", en: "Kurdistan"}},
  { id: 21, name: {fa: "کرمان", en: "Kerman"}},
  { id: 22, name: {fa: "کرمانشاه", en: "Kermanshah"}},
  { id: 23, name: {fa: "کهگیلویه و بویراحمد", en: "Kohgiluyeh and Boyer-Ahmad"}},
  { id: 24, name: {fa: "گلستان", en: "Golestan"}},
  { id: 25, name: {fa: "گیلان", en: "Gilan"}},
  { id: 26, name: {fa: "لرستان", en: "Lorestan"}},
  { id: 27, name: {fa: "مازندران", en: "Mazandaran"}},
  { id: 28, name: {fa: "مرکزی", en: "Markazi"}},
  { id: 29, name: {fa: "هرمزگان", en: "Hormozgān"}},
  { id: 30, name: {fa: "همدان", en: "Hamadan"}},
  { id: 31, name: {fa: "یزد", en: "Yazd"}},
]
